### PR TITLE
Add getFileInfo implementation

### PR DESCRIPTION
**Pull request by jarodium**

### CODE REVIEW

**Comment by Savjee** [comment]
Thanks for the pull request! getFileInfo() works just fine.

Have one small question about getFileVersions() though. The BackBlaze docs stay that the delimiter is optional. Should it be optional in your code as well? If yes, can you quickly update it. Then I can merge ;)

**Comment by jarodium** [comment]
Sorry about it. 
That and the fix for the prefix adding condition. I have fixed it. xD

Thanks for pointing it out

**Comment by Savjee** [comment]
Looks great! Thanks for your contribution! Maybe I should pick this project back up and make it a complete PHP implementation for B2.

**Comment by jarodium** [comment]
Good to hear it.
Meanwhile I will implement some of the methods the api provides and post them back in Github.
At this time I'm not thinking of implementing all of them, because my current needs to use b2's api are small.

**Pull request merged**
